export { default as Input1 } from "./Input/Input1"
export { default as Input2 } from "./Input/Input2"
export { default as Input3 } from "./Input/Input3"
export { default as Input4 } from "./Input/Input4"
export { default as InputForm } from "./Input/InputForm"
